version: "3"

services:

  vulnogram-mongo:
    image: mongo:6
    command: mongod --port ${MONGO_PORT:-27017}
    restart: always
    volumes:
      - vulnogram-mongo-data:/data/db
    env_file:
      - ${ENV_VAR_PATH:-example.env}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:${MONGO_PORT:-27017}/vulnogram --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}

  vulnogram:
    build: .
    image: vulnogram/vulnogram:latest

    container_name: vulnogram

    ports:
      - ${VULNOGRAM_PORT:-3555}:${VULNOGRAM_PORT:-3555}

    env_file:
      - ${ENV_VAR_PATH:-example.env}

    depends_on:
      vulnogram-mongo:
        condition: service_healthy

volumes:
  vulnogram-mongo-data:
